"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const faqs = [
  {
    question: "How much can I save by switching to solar?",
    answer:
      "With a properly installed solar system, you can save up to 80% on your monthly electricity bills. In many cases, users even export excess electricity back to the grid through net metering, earning additional credits.",
  },
  {
    question: "Is my roof suitable for solar panels?",
    answer:
      "If your roof receives sunlight for at least 4–5 hours daily and is free from large shadows (like trees or buildings), it’s ideal for solar. Our experts provide a free site survey to assess roof angle, strength, and sun path.",
  },
  {
    question: "What is net metering and why is it important?",
    answer:
      "Net metering is a billing mechanism where excess energy generated by your solar panels is sent back to the electricity grid. You earn credits that reduce your electricity bill, making your solar investment more profitable.",
  },
  {
    question: "Can I get a subsidy from the government?",
    answer:
      "Yes. Under the MNRE (Ministry of New and Renewable Energy) scheme, residential users can get up to 40% subsidy. We handle the complete subsidy process for you — including documentation and government liaison.",
  },
  {
    question: "What’s the installation timeline?",
    answer:
      "After site survey and documentation, a typical rooftop solar installation takes 5–7 working days. This includes panel mounting, inverter setup, net metering application, and final inspection.",
  },
];

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-20 px-4 sm:px-6 md:px-12 bg-white font-[Rubik]">
      <div className="max-w-3xl mx-auto text-center">
        <p className="text-[#89EA5F] font-semibold uppercase tracking-wide mb-2 text-sm sm:text-base">
          💡 Frequently Asked
        </p>
        <h2 className="text-3xl sm:text-4xl text-[#101010] mb-8 leading-tight">
          Smart Questions. Honest Answers.
        </h2>
      </div>

      <div className="max-w-3xl mx-auto mt-6 space-y-4">
        {faqs.map((faq, index) => (
          <div
            key={index}
            className="border border-gray-200 rounded-xl shadow-md transition-all duration-200"
          >
            <button
              onClick={() => toggleFAQ(index)}
              className="w-full flex justify-between items-center px-4 sm:px-6 py-4 text-left text-base sm:text-lg font-medium text-[#101010] hover:text-[#89EA5F] transition"
            >
              {faq.question}
              <ChevronDown
                className={`w-5 h-5 transition-transform duration-300 ease-in-out ${
                  openIndex === index ? "rotate-180 text-[#89EA5F]" : ""
                }`}
              />
            </button>

            <AnimatePresence initial={false}>
              {openIndex === index && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.3, ease: "easeInOut" }}
                  className="overflow-hidden px-4 sm:px-6 pb-4 text-gray-600 text-sm sm:text-base leading-relaxed"
                >
                  {faq.answer}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        ))}
      </div>
    </section>
  );
}
